# Generated by Django 5.1.5 on 2025-01-22 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('R', 'Regular'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pastasvariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cafe/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('SP', 'Spaghetti Bolognese'), ('CP', 'Creamy Fettuccine Alfredo'), ('MP', 'Macaroni & Cheese'), ('PP', 'Pesto Pasta'), ('CM', 'Classic Masala Maggi'), ('BM', 'Butter Garlic Maggi'), ('ChM', 'Cheese Maggi'), ('VDM', 'Veggie Delight Maggi'), ('SSM', 'Spicy Schezwan Maggi'), ('PM', 'Paneer Maggi')], max_length=3)),
                ('desc', models.TextField(default='')),
                ('price', models.IntegerField(default=0, verbose_name='FoodPrice')),
                ('sizes', models.ManyToManyField(related_name='Pastasvariety', to='Food_App.foodsize')),
            ],
        ),
        migrations.CreateModel(
            name='Side_dishvariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cafe/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('FN', 'French Fries'), ('GC', 'Garlic Bread'), ('NM', 'Nachos with Cheese'), ('SM', 'Samosas'), ('CB', 'Cheese Balls'), ('PM', 'Popcorn')], max_length=4)),
                ('desc', models.TextField(default='')),
                ('price', models.IntegerField(default=0, verbose_name='FoodPrice')),
                ('sizes', models.ManyToManyField(related_name='Side_dishvariety', to='Food_App.foodsize')),
            ],
        ),
        migrations.CreateModel(
            name='Snacksvariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cafe/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('CB', 'Chicken Burger'), ('BG', 'BBQ Chicken Wrap'), ('GR', 'Grilled Cheese Sandwich'), ('VB', 'Veggie Burger'), ('PB', 'Paneer Tikka Wrap')], max_length=3)),
                ('desc', models.TextField(default='')),
                ('price', models.IntegerField(default=0, verbose_name='FoodPrice')),
                ('sizes', models.ManyToManyField(related_name='Snacksvariety', to='Food_App.foodsize')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_App.foodsize')),
                ('Pastas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.pastasvariety')),
                ('Side_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.side_dishvariety')),
                ('Snacks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.snacksvariety')),
            ],
        ),
        migrations.CreateModel(
            name='AddFoodToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_App.foodsize')),
                ('Pastas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.pastasvariety')),
                ('Side_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.side_dishvariety')),
                ('Snacks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.snacksvariety')),
            ],
        ),
    ]
