# Generated by Django 5.1.5 on 2025-01-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side_dishvariety',
            name='type',
            field=models.CharField(choices=[('FN', 'French Fries'), ('GC', 'Garlic Bread'), ('NM', 'Nachos with Cheese'), ('SM', 'Samosas'), ('CB', 'Cheese Balls'), ('CP', 'Classic Pizza')], max_length=4),
        ),
    ]
