# Generated by Django 5.1.5 on 2025-01-21 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='teavariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cafe/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('GB', 'Green Tea'), ('BL', 'Black Tea'), ('WH', 'White Tea'), ('OL', 'Oolong Tea'), ('MR', 'Matcha'), ('CH', 'Chai'), ('DA', 'Darjeeling'), ('HB', 'Herbal Tea'), ('LF', 'Lemon Verbena')], max_length=3)),
                ('desc', models.TextField(default='')),
                ('price', models.IntegerField(default=0, verbose_name='TeaPrice')),
                ('sizes', models.ManyToManyField(related_name='teavariety', to='Tea_App.size')),
            ],
        ),
        migrations.CreateModel(
            name='TeaPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tea_App.size')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tea_App.teavariety')),
            ],
        ),
        migrations.CreateModel(
            name='AddTeaToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tea_App.size')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tea_App.teavariety')),
            ],
        ),
    ]
