# Generated by Django 5.1.5 on 2025-01-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='TeaSize',
        ),
    ]
