# Generated by Django 5.1.5 on 2025-01-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0002_rename_size_teasize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teavariety',
            name='type',
            field=models.CharField(choices=[('GB', 'Green Tea'), ('BL', 'Black Tea'), ('WH', 'White Tea'), ('OL', 'Oolong Tea'), ('MR', 'Matcha'), ('CH', 'Chai'), ('DA', 'Darjeeling'), ('HB', 'Herbal Tea'), ('LF', 'Lemon Verbena'), ('AS', 'Assam Tea'), ('NI', 'Nilgiri Tea'), ('KJ', 'Kashmiri Kahwa'), ('CL', 'Chrysanthemum Tea'), ('MA', 'Masala Chai'), ('TT', 'Tandoori Chai')], max_length=3),
        ),
    ]
