# Generated by Django 5.1.5 on 2025-01-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoldApp', '0001_initial'),
        ('Tea_App', '0002_rename_size_teasize'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='tea_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tea_App.teasize'),
        ),
    ]
