# Generated by Django 5.1.5 on 2025-01-21 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0001_initial'),
        ('SoldApp', '0002_solditem_tea_size'),
        ('Tea_App', '0002_rename_size_teasize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='tea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tea_App.teavariety'),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='card_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='coffee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CafeApp.coffeevariety'),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CafeApp.size'),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='sold_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
