# Generated by Django 5.1.5 on 2025-01-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Other_Beverage', '0001_initial'),
        ('SoldApp', '0003_solditem_tea_alter_solditem_card_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='beverage_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.beavragesize'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='hot_chocolate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.hot_chocolatesvariety'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='juice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.juicesvariety'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='milkshake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.milkshakesvariety'),
        ),
    ]
