# Generated by Django 5.1.5 on 2025-01-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_App', '0001_initial'),
        ('SoldApp', '0004_solditem_beverage_size_solditem_hot_chocolate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='Pastas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.pastasvariety'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='Side_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.side_dishvariety'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='Snacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.snacksvariety'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='food_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_App.foodsize'),
        ),
    ]
