# Generated by Django 5.1.5 on 2025-01-22 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeavrageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hot_Chocolatesvariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cafe/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('CHC', 'Classic Hot Chocolate'), ('WHC', 'White Hot Chocolate'), ('HHC', 'Hazelnut Hot Chocolate'), ('NHC', 'Nutella Hot Chocolate'), ('ALHC', 'Almond Hot Chocolate'), ('CCHC', 'Cookies & Cream Hot Chocolate')], max_length=4)),
                ('desc', models.TextField(default='')),
                ('price', models.IntegerField(default=0, verbose_name='BeavragePrice')),
                ('sizes', models.ManyToManyField(related_name='Hot_Chocolatesvariety', to='Other_Beverage.beavragesize')),
            ],
        ),
        migrations.CreateModel(
            name='juicesvariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cafe/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('AJ', 'Apple Juice'), ('OJ', 'Orange Juice'), ('MJ', 'Mango Juice'), ('PJ', 'Pineapple Juice'), ('MFJ', 'Mixed Fruit Juice'), ('SMJ', 'Strawberry Juice'), ('WJ', 'Watermelon Juice')], max_length=3)),
                ('desc', models.TextField(default='')),
                ('price', models.IntegerField(default=0, verbose_name='BeavragePrice')),
                ('sizes', models.ManyToManyField(related_name='juicesvariety', to='Other_Beverage.beavragesize')),
            ],
        ),
        migrations.CreateModel(
            name='Milkshakesvariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cafe/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('CM', 'Chocolate Milkshake'), ('VM', 'Vanilla Milkshake'), ('SM', 'Strawberry Milkshake'), ('BM', 'Banana Milkshake'), ('OCM', 'Oreo Cookies & Cream Milkshake'), ('NM', 'Nutella Milkshake'), ('MM', 'Mango Milkshake')], max_length=3)),
                ('desc', models.TextField(default='')),
                ('price', models.IntegerField(default=0, verbose_name='BeavragePrice')),
                ('sizes', models.ManyToManyField(related_name='Milkshakesvariety', to='Other_Beverage.beavragesize')),
            ],
        ),
        migrations.CreateModel(
            name='BeavragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.beavragesize')),
                ('hot_chocolate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.hot_chocolatesvariety')),
                ('juice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.juicesvariety')),
                ('milkshake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.milkshakesvariety')),
            ],
        ),
        migrations.CreateModel(
            name='AddBeavrageToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.beavragesize')),
                ('hot_chocolate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.hot_chocolatesvariety')),
                ('juice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.juicesvariety')),
                ('milkshake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Other_Beverage.milkshakesvariety')),
            ],
        ),
    ]
